import { useState } from 'react'
import { CheckCircle2, ShieldCheck, UploadCloud } from 'lucide-react'
import FormField from '../../components/FormField'
import { useToast } from '../../context/ToastContext'
import { dataService } from '../../services/dataService'

export default function PaymentPage() {
  const [form, setForm] = useState({ payer_name: '', payer_phone: '', reference_number: '', amount: '', notes: '' })
  const [file, setFile] = useState(null)
  const [errors, setErrors] = useState({})
  const [result, setResult] = useState(null)
  const { show } = useToast()
  const submit = async (event) => { event.preventDefault(); const next = {}; if (form.payer_name.trim().length < 2) next.payer_name = 'Ingrese el nombre de quien realizó el pago.'; if (!/^\d{8}$/.test(form.payer_phone)) next.payer_phone = 'El teléfono debe contener 8 dígitos.'; if (form.reference_number.trim().length < 4) next.reference_number = 'Ingrese una referencia de al menos 4 caracteres.'; if (Number(form.amount) <= 0) next.amount = 'El monto debe ser mayor que cero.'; if (!file) next.file = 'Adjunte el comprobante.'; setErrors(next); if (Object.keys(next).length) return show('Revise los datos del pago.', 'error'); try { const payment = await dataService.createPayment({ ...form, amount: Number(form.amount) }, file); setResult(payment); show('Comprobante enviado correctamente.') } catch (error) { show(error.message, 'error') } }
  if (result) return <section className="page-section narrow"><div className="success-panel"><CheckCircle2 /><p className="eyebrow">Comprobante recibido</p><h1>{result.reference_number}</h1><p>El pago se registró con estado <strong>Pendiente</strong>. Un administrador debe comprobarlo antes de confirmarlo.</p></div></section>
  return <section className="page-section form-page"><div className="form-intro"><span><ShieldCheck /></span><p className="eyebrow">Validación manual</p><h1>Reporte su pago SINPE</h1><p>Este formulario no realiza transferencias. Registra el comprobante para que VendeloTodo lo revise.</p><aside className="notice"><strong>Datos SINPE</strong><span>Número de prueba: 8888-0000</span><span>A nombre de: VendeloTodo QA</span><small>Reemplace estos datos en producción.</small></aside></div><form className="panel-form" onSubmit={submit} noValidate><div className="form-grid"><FormField label="Nombre del pagador" required error={errors.payer_name}><input value={form.payer_name} onChange={(e) => setForm({ ...form, payer_name: e.target.value })} /></FormField><FormField label="Teléfono" required error={errors.payer_phone}><input inputMode="numeric" value={form.payer_phone} onChange={(e) => setForm({ ...form, payer_phone: e.target.value.replace(/\D/g, '').slice(0, 8) })} /></FormField><FormField label="Número de referencia" required error={errors.reference_number}><input maxLength={80} value={form.reference_number} onChange={(e) => setForm({ ...form, reference_number: e.target.value })} /></FormField><FormField label="Monto en colones" required error={errors.amount}><input type="number" min="1" step="1" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></FormField><FormField label="Notas"><textarea rows="3" maxLength={500} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></FormField><FormField label="Comprobante" required error={errors.file} hint="JPG, PNG o PDF; máximo 5 MB"><label className="file-drop"><UploadCloud /><span>{file ? file.name : 'Seleccione un archivo'}</span><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label></FormField></div><button className="button button--primary button--full">Enviar comprobante</button></form></section>
}
