import { useEffect, useState } from 'react'
import { CheckCircle2, Star } from 'lucide-react'
import FormField from '../../components/FormField'
import { useToast } from '../../context/ToastContext'
import { dataService } from '../../services/dataService'
import { formatDate } from '../../utils/formatters'

export default function ReviewsPage() {
  const [reviews, setReviews] = useState([])
  const [services, setServices] = useState([])
  const [form, setForm] = useState({ customer_name: '', service_id: '', rating: 5, comment: '' })
  const [errors, setErrors] = useState({})
  const [sent, setSent] = useState(false)
  const { show } = useToast()
  useEffect(() => { Promise.all([dataService.getReviews(), dataService.getServices()]).then(([r, s]) => { setReviews(r); setServices(s) }) }, [])
  const submit = async (event) => { event.preventDefault(); const next = {}; if (form.customer_name.trim().length < 2) next.customer_name = 'Ingrese su nombre.'; if (!form.service_id) next.service_id = 'Seleccione el servicio recibido.'; if (form.comment.trim().length < 10) next.comment = 'El comentario debe tener al menos 10 caracteres.'; setErrors(next); if (Object.keys(next).length) return show('Revise los campos de la reseña.', 'error'); try { await dataService.createReview(form); setSent(true); show('Reseña enviada a moderación.') } catch (error) { show(error.message, 'error') } }
  return <section className="page-section"><div className="page-hero compact"><p className="eyebrow">Opiniones verificables</p><h1>Experiencias de nuestros clientes</h1><p>Solo se muestran reseñas aprobadas. Cada nueva opinión queda pendiente de moderación.</p></div><div className="reviews-layout"><div className="review-list">{reviews.map((review) => <article key={review.id}><div className="stars">{Array.from({ length: review.rating }, (_, i) => <Star key={i} fill="currentColor" />)}</div><blockquote>“{review.comment}”</blockquote><footer><strong>{review.customer_name}</strong><span>{review.service_name} · {formatDate(review.created_at)}</span></footer></article>)}</div><aside className="review-form"><h2>Comparta su experiencia</h2>{sent ? <div className="inline-success"><CheckCircle2 /><strong>Gracias por su opinión.</strong><p>Se publicará únicamente si el administrador la aprueba.</p><button type="button" className="text-link" onClick={() => { setSent(false); setForm({ customer_name: '', service_id: '', rating: 5, comment: '' }) }}>Enviar otra reseña</button></div> : <form onSubmit={submit} noValidate><FormField label="Nombre" required error={errors.customer_name}><input value={form.customer_name} onChange={(e) => setForm({ ...form, customer_name: e.target.value })} /></FormField><FormField label="Servicio" required error={errors.service_id}><select value={form.service_id} onChange={(e) => setForm({ ...form, service_id: e.target.value })}><option value="">Seleccione</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></FormField><FormField label="Calificación" required><select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })}>{[5,4,3,2,1].map((value) => <option key={value} value={value}>{value} {value === 1 ? 'estrella' : 'estrellas'}</option>)}</select></FormField><FormField label="Comentario" required error={errors.comment}><textarea rows="5" maxLength={800} value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} /></FormField><button className="button button--primary button--full">Enviar a moderación</button></form>}</aside></div></section>
}
